### ISSUE TITLE
Syntax error when run `ruby ./dnscat2.rb`

### ISSUE THREAD

**Issue by ourlord** [iagox86/dnscat2#101]
Follow the steps in the page. Run as root. Gem and install bundler doesn't have any issue. Issue happened when run `ruby ./dnscat2.rb` from the first time. 

```
New window created: 0
./controller/controller.rb:11:in `require': ./controller/controller_commands.rb:29: syntax error, unexpected ')' (SyntaxError)
./controller/controller_commands.rb:50: syntax error, unexpected ')'
	from ./controller/controller.rb:11
	from ./dnscat2.rb:18:in `require'
	from ./dnscat2.rb:18
```

My ruby version: `ruby 1.8.7 (2012-02-08 MBARI 8/0x6770 on patchlevel 358) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2012.02`. Gem is 2.6.6. Bundle version 1.13.1.

**Comment by iagox86** [comment]
Can you try upgrading to Ruby 1.9 and see if that helps?

I try hard to maintain reverse compatibility, but right now I'm testing on
1.9 and later, not 1.8.

**Comment by ourlord** [comment]
Seems to work after migrate from ruby 1.8 to 1.9. Thanks a lot.
