### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by SirMcGruff** [iagox86/dnscat2#109]
Anyone have a documented why to get this installed?  I am having issues with the ruby/gems part.  Ubuntu 14, but can use any version as long as it works.  Trying to install the server part.

**Comment by iagox86** [comment]
I'm working on making this much easier, but in the meantime, I agree, it's
kinda bad.

I find that rvm works best. You can install rvm from https://rvm.io, then
install ruby and gems under your current account. I typically use 'su' to
switch to root, then run all of the commands.

I don't have a clean system right now to do a step by step, but give rvm a
shot.

**Comment by SirMcGruff** [comment]
OK so i got the server finally installed..... i will see about working on a script as that was painful getting the depends installed

**Comment by iagox86** [comment]
It's kinda late, but "bundle install" might have been what you needed. And
possibly "gem install bundler" first. Sorry, I didn't think of mentioning
that. :)
