### ISSUE TITLE
Implement Option for DNS over HTTPS

### ISSUE THREAD

**Issue by felixguerrero12** [iagox86/dnscat2#133]
Google and Cloudfare both have implementation of DNS over HTTPS and was wondering if it can be used as an implementation to this tool. This tool can be leveraged using the running cloudflared proxy-dns then dnscat --dns server=127.0.0.1,domain=skullseclabs.org --ping.
https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/

Client ---> Encrypted DNS over HTTPS to Cloudflare --> The Skullseclabs DNS Server
----
https://developers.google.com/speed/public-dns/docs/dns-over-https
https://developers.cloudflare.com/1.1.1.1/dns-over-https/
----
Requesting for this method to simulate the traffic as HTTPS Traffic.
This should also bypass corporate that uses solely internal DNS Server.

**Comment by iagox86** [comment]
Yeah, I'd really like to. But I've been pretty idle on this project lately,
unfortunately. I'll get to super cool new features eventually, though!
