### ISSUE TITLE
Change WILDCARD_PREFIX "dnscat"

### ISSUE THREAD

**Issue by Pouya47** [iagox86/dnscat2#138]
How we can change WILDCARD_PREFIX "dnscat" for by pass IPS detection?
when i change it to something like "anscat" I get this error:
[[ ERROR ]] :: The server hasn't returned a valid response in the last 20 attempts.. closing session.

**Comment by iagox86** [comment]
I tend to count evading a/v as "an exercise for the reader" :)

You have to change both the client and the server, though.
