### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [iagox86/dnscat2#164]
It has been a while (five years) since last beta release, I wonder if there is any new release plan, also I can help introduce this tool into homebrew-core, thanks!

---

relates to
- #161

**Comment by iagox86** [comment]
I think it's pretty safe to say at point that it's more or less abandoned,
at least by me. I started a new version in Rust, but it's low priority.

**Comment by chenrui333** [comment]
I see, that is good to know. Closing my issue then. Thanks!
