### ISSUE TITLE
Write a guide on how to set up an authoritative server

### ISSUE THREAD

**Issue by iagox86** [iagox86/dnscat2#28]

**Comment by gabemarshall** [comment]
This is what I've used in the past. Pretty straight forward.

https://www.digitalocean.com/community/tutorials/how-to-configure-bind-as-an-authoritative-only-dns-server-on-ubuntu-14-04

**Comment by iagox86** [comment]
Sweet! The section called "Delegate Authority to your Name Servers" is what I'm really looking for, I'll have to add a link to it to a doc somewhere

**Comment by iagox86** [comment]
izhan fixed this some time ago.
