### ISSUE TITLE
Client Segfault

### ISSUE THREAD

**Issue by Scoubi** [iagox86/dnscat2#4]
$ gdb --args ./dnscat --host 1.1.1.1 foobar.com
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
Reading symbols from /home/user/dnscat2/client/dnscat...done.
(gdb) run
Starting program: /home/user/dnscat2/client/dnscat --host 1.1.1.1 foobar.com
[[ WARNING ]] :: INPUT: Command
[[ WARNING ]] :: Session successfully created: 22552
[[ WARNING ]] :: Session creation request
[[ WARNING ]] :: Setting config: max_packet_length => 109
[[ WARNING ]] :: OUTPUT: DNS tunnel to foobar.com
Got a command: COMMAND_PING [request] :: request_id: 0x0001 :: data: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Got a ping request! Responding!
Response: COMMAND_PING [response] :: request_id: 0x0001 :: data: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Program received signal SIGSEGV, Segmentation fault.
handle_message (message=<error reading variable: Cannot access memory at address 0x7ffeffffffe8>, 
    message@entry=<error reading variable: Cannot access memory at address 0x7fff00000008>, 
    d=<error reading variable: Cannot access memory at address 0x7ffeffffffe0>, 
    d@entry=<error reading variable: Cannot access memory at address 0x7fff00000008>)
    at driver_command.c:137
137     }

**Comment by iagox86** [comment]
I used to be able to repro 100% of the time on my work computer. Then I didn't touch this bug for months, but made a ton of other fixes. Now I can't repro anymore. Here's hoping it's accidentally fixed! :)

**Comment by Scoubi** [comment]
I'll look into it next week, thanks dude :)




---
Web Site : www.travelhard.com

**Comment by Scoubi** [comment]
Hi,

I just reinstall dnscat2 on a new server. Pull the new code on the client
and compile


-rwxr-xr-x 1 mats users 243821 Jan 20 14:41 dnscat

I'm using IP not DNS and it still crash.

mats@Vinos-223:~/dnscat2/server$ sudo ruby dnscat2.rb --dnshost
68.67.61.223 -e info

mats@insomniac:~/dnscat2/client$ ./dnscat --host 68.67.61.223 -d

I've attached the two screen capture.

I'll wait until my domain is pointed to the new IP and will let you know if
it works.

Hope it helps...

Mat.


---
Web Site : www.travelhard.com

**Comment by iagox86** [comment]
Crazy, I can't repro! Which OS? I'll make a VM. I want this solved before I
release an official version!

**Comment by Scoubi** [comment]
Client

mats@insomniac:~/dns2tcp-0.5.2/client$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

Server

mats@Vinos-223:~$ nc --version
nc: invalid option -- '-'
nc -h for help
mats@Vinos-223:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux Kali Linux 1.0.9
Release:        Kali Linux 1.0.9
Codename:       n/a




---
Web Site : www.travelhard.com

**Comment by iagox86** [comment]
Cool, I'll grab that version of Ubuntu and give it a shot!

Any specific configuration/installation options that might affect things?
Any updates after installing?

FWIW, I'm in the process of moving and most of my gear is packed up. I
don't expect to get to this for a week or two. :)

**Comment by Scoubi** [comment]
You know, if you want I can share my screen.

The problem might be with the configuration of my domain (or lack of)

I beleive both system are fully updated (I'm root on the server not on the
client)



---
Web Site : www.travelhard.com

**Comment by iagox86** [comment]
Whether your domain is configured right or wrong, it shouldn't cause the
client to segfault. That's a problem with the client, for sure.

Can you stand up the dnscat server right now, and give me the info to
connect to it? I'll do a quick test to see if I can get the client to crash
on my end. If I can, then we're golden!

**Comment by Scoubi** [comment]
Here's the coredump


---
Web Site : www.travelhard.com

**Comment by Scoubi** [comment]
Hey!

Me again. this time with a good news. I just save you some reverse
engeneering / linux install and other headaches.

After recompiling dnscat on the saver it seems the problem is now fixed.

Look at this beatifull output : mats@insomniac:~/dnscat2/client$ ./dnscat
t.hehe.ca
[[ WARNING ]] :: INPUT: Command
[[ WARNING ]] :: Session successfully created: 19730
[[ WARNING ]] :: Session creation request
[[ WARNING ]] :: Setting config: max_packet_length => 112
[[ WARNING ]] :: OUTPUT: DNS tunnel to t.hehe.ca via 127.0.0.1:53
Got a command: COMMAND_EXEC [request] :: request_id: 0x0001 :: name:
executing ls :: command: ls
[[ WARNING ]] :: Session successfully created: 3025
[[ WARNING ]] :: Session creation request
[[ WARNING ]] :: Started: ls (pid: 763)
Response: COMMAND_EXEC [response] :: request_id: 0x0001 :: session_id:
0x0bd1
[[ WARNING ]] :: Session closure request: 3025
[[ WARNING ]] :: Session 3025 is out of data and closed, killing it!
[[ WARNING ]] :: Trying to close a closed session: 3025
[[ WARNING ]] :: Session closure request: 3025
[[ ERROR ]] :: Tried to access a non-existent session (handle_packet_in):
3025
[[ ERROR ]] :: Tried to access a non-existent session (handle_packet_in):
3025
Got a command: COMMAND_PING [request] :: request_id: 0x0002 :: data:
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Got a ping request! Responding!
Response: COMMAND_PING [response] :: request_id: 0x0002 :: data:
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

I guess I pulled the new code but forgot to recompile / make clean

Anyway, seems you are ready for a release! :)

Hope your new home is nice and that the moving went well!

Yes, it's 6:40 am here and I'm awake since 5am. Thanks to ybaby girl...

Take care,
Mat.


---
Web Site : www.travelhard.com
