### ISSUE TITLE
Session management problem when server restarts

### ISSUE THREAD

**Issue by ithilgore** [iagox86/dnscat2#47]
Dnscat2 client is left hanging if server is restarted, although normal behavior would be to try to reconnect. 
I coded a temporary workaround which wraps around the main client loop, checking for timeouts (the heartbeat mechanism wasn't enough apparently) and though it is working in most cases, the server gets a lot of extra sessions which are left hanging and are proportionate to the number of times the server has been restarted.

In addition, the server prints the "SYN received in invalid state" (which is ignored), "Bad sequence number on incoming packet" and "FIN received in non-existent session". The above are triggered probably because the client (since no process restarting has taken place on its part) still keeps its previous state and it doesn't eventually clear them, thus resulting in the proportionate increase of round-trip packets.

**Comment by iagox86** [comment]
Client-cleanup branch has better behaviour.. I plan to merge it soon. :-)

**Comment by iagox86** [comment]
This should be fixed when I merge client-cleanup (which will be soon)... the client will eventually give up if it can't connect rather than connecting forever. Making the session management better will be easier now, too!

**Comment by willem-tee** [comment]
Sorry to reopen this, if you'd like me to open a new thread please let me know. It might be a different issue after all.

When I close down the server with an active connection to a client and restart the server, I was expecting the client to be able to reconnect. I have passed the --secret to the client, established previously with "set secret" in the server. I have also tried without the --secret parameter.

The client retries for about 15-20 times and closes down. These are the logs/messages in the client:

Session established!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ ERROR ]] :: The server hasn't returned a valid response in the last 20 attempts.. closing session.
[[ WARNING ]] :: Tried to kill a session that's already dead: 5889
[[ WARNING ]] :: Server's signature was wrong! Ignoring!
[[ FATAL ]] :: There are no active sessions left! Goodbye!
[[ WARNING ]] :: Terminating

Is there a way to reconnect to the server when it faces a shutdown? 

Thanks

**Comment by willem-tee** [comment]
If I pass both flags in client and server "--retransmit-forever --no-encryption" and "--security=open" and I close down the server and reopen it, the client does not show any errors but the server does.

> dnscat2>
 New window created: 1
An error occurred (see window 1 for stacktrace): MSG received in invalid state!
An error occurred (see window 1 for stacktrace): MSG received in invalid state!
An error occurred (see window 1 for stacktrace): MSG received in invalid state!
windoAn error occurred (see window 1 for stacktrace): MSG received in invalid state!
ws
0 :: main [active]
  crypto-debug :: Debug window for crypto stuff [*]
  dns1 :: DNS Driver running on 0.0.0.0:53 domains = blabladomain.com [*]
  1 :: (**not set**) [cleartext] [*]


Now if I pass "session -i 1" I will get this over and over in the server until I Ctrl+z:

> If you think this might be a bug, please report this trace:
#<DnscatException: MSG received in invalid state!>
/root/dnscat2/server/controller/session.rb:207:in `_handle_msg'
/root/dnscat2/server/controller/session.rb:387:in `_handle_incoming'
/root/dnscat2/server/controller/session.rb:405:in `block in feed'
/root/dnscat2/server/controller/encryptor.rb:244:in `decrypt_and_encrypt'
/root/dnscat2/server/controller/session.rb:395:in `feed'
/root/dnscat2/server/controller/controller.rb:91:in `feed'
/root/dnscat2/server/tunnel_drivers/tunnel_drivers.rb:25:in `block in start'
/root/dnscat2/server/tunnel_drivers/driver_dns.rb:316:in `block in initialize'
/root/dnscat2/server/libs/dnser.rb:872:in `block (2 levels) in on_request'
/root/dnscat2/server/libs/dnser.rb:843:in `loop'
/root/dnscat2/server/libs/dnser.rb:843:in `block in on_request'
/root/dnscat2/server/libs/swindow.rb:381:in `join': Interrupt
	from /root/dnscat2/server/libs/swindow.rb:381:in `wait'
	from ./dnscat2.rb:215:in `<main>'

As a final note, as you said yesterday you are very busy these days and I understand :) great project you have here, no complains whatsoever. It's just that my understanding is that reliability is a core aspect in any application. 

If it's me that is messing it up and doesn't know how to make it work I apologise, might as well be!

Thanks
