### ISSUE TITLE
Type A DNS record character encoding problem

### ISSUE THREAD

**Issue by ithilgore** [iagox86/dnscat2#48]
Using type A records in dnscat2 client, results in the server responding with "No such name" due to its failing to understand the A query due to incompatible character encoding:

Client:
./dnscat <domain>  --type A
[[ ERROR ]] :: DNS: RCODE_NAME_ERROR

Server:
ruby ./dnscat2.rb <domain>

New session established: 57993
[ERROR] Error caught:
[ERROR] [Encoding::CompatibilityError]: incompatible character encodings: ASCII-8BIT and UTF-8
[ERROR] /home/ithilgore/Downloads/dnscat2-master/server/driver_dns.rb:67:in `ljust'
[ERROR] /home/ithilgore/Downloads/dnscat2-master/server/driver_dns.rb:67:in `block (2 levels) in <class:DriverDNS>'
[ERROR] /home/ithilgore/Downloads/dnscat2-master/server/driver_dns.rb:66:in `map'
[ERROR] /home/ithilgore/Downloads/dnscat2-master/server/driver_dns.rb:66:in `block in <class:DriverDNS>'
[ERROR] /home/ithilgore/Downloads/dnscat2-master/server/driver_dns.rb:236:in `call'
[ERROR] /home/ithilgore/Downloads/dnscat2-master/server/driver_dns.rb:236:in `block (2 levels) in recv'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:170:in `[]'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:170:in `call'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:277:in `block (2 levels) in process'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:275:in `catch'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:275:in `block in process'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:272:in `each'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:272:in `process'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/transaction.rb:210:in `process'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:84:in `block (2 levels) in process_query'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:79:in `each'
[ERROR] /var/lib/gems/2.1.0/gems/rubydns-0.7.3/lib/rubydns/server.rb:79:in `block in process_query'

**Comment by iagox86** [comment]
Hmm, I thought that that was fixed in a recent pull request! We must have
missed something, I'll check it out :)

**Comment by iagox86** [comment]
Hey, I can't repro this, but I tried to fix it in f42a7e2f37e - can you see if there's still a problem?

**Comment by iagox86** [comment]
I'm going to assume this was fixed in that revision - feel free to re-open!
