### ISSUE TITLE
Can't connect to the server from abroad

### ISSUE THREAD

**Issue by slglayglay** [iagox86/dnscat2#8]
Hi, 

I set up the server in my office and connect to it from my apartment. Everything works fine.  

But when I tested with my friends from Nigeria and China, both cannot connect to my server. I have attached the screenshots from the client side when connected from China. I forget to save the screenshot of the server side. I will test it again tomorrow.
![get_offpic2](https://cloud.githubusercontent.com/assets/3586185/3529235/9d580c6a-0797-11e4-8efc-6c05dbdc6d53.jpeg)

Any idea?

Thanks,
Lu

**Comment by iagox86** [comment]
So, I've made a bunch of changes to how the direct connections work, and how the domains are parsed. Hopefully this all works now, feel free to re-open if it's still broken and you're still trying to do this. :)
