### ISSUE TITLE
download/upload instructions

### ISSUE THREAD

**Issue by rudeyak** [iagox86/dnscat2#81]
When a session is established, the instructions for upload/download are somewhat ambiguous:
> command (victimPC) 2> upload -h
> Error: The user requested help
> Upload a file off the remote host. Usage: upload <from> <to>
>   -h, --help    Show this message
> command (victimPC) 2> download -h
> Error: The user requested help
> Download a file off the remote host. Usage: download <from> [to]
>   -h, --help    Show this message

Suggestion:
<pre>
*** driver_command_commands.rb.orig     2015-11-22 07:27:35.467533912 -0600
--- driver_command_commands.rb  2015-11-22 07:41:30.738750647 -0600
***************
*** 147,153 ****

      @commander.register_command("download",
        Trollop::Parser.new do
!         banner("Download a file off the remote host. Usage: download <from> [to]")
        end,

        Proc.new do |opts, optarg|
--- 147,153 ----

      @commander.register_command("download",
        Trollop::Parser.new do
!         banner("Request the client to send a file to the server. Usage: download <from> [to]")
        end,

        Proc.new do |opts, optarg|
***************
*** 185,191 ****

      @commander.register_command("upload",
        Trollop::Parser.new do
!         banner("Upload a file off the remote host. Usage: upload <from> <to>")
        end,

        Proc.new do |opts, optarg|
--- 185,191 ----

      @commander.register_command("upload",
        Trollop::Parser.new do
!         banner("Deliver a file from the server to the client's local filesystem. Usage: upload <from> <to>")
        end,

        Proc.new do |opts, optarg|
</pre>

This will result in:
> command (victimPC) 1> upload -h
> Error: The user requested help
> Deliver a file from the server to the client's local filesystem. Usage: upload <from> <to>
>   -h, --help    Show this message
> command (victimPC) 1> download -h
> Error: The user requested help
> Request the client to send a file to the server. Usage: download <from> [to]
>   -h, --help    Show this message

**Comment by iagox86** [comment]
Hey, are you using the most recent version (either 0.04 or git)? For me, the help for upload and download look fine:

    command (Ron-PC) 1> upload -h
    Error: The user requested help
    Upload a file off the remote host. Usage: upload <from> <to>
      -h, --help    Show this message
    command (Ron-PC) 1> download -h
    Error: The user requested help
    Download a file off the remote host. Usage: download <from> [to]
      -h, --help    Show this message

If you're not seeing that, then there must be something different about the command-parsing library I'm using (Trollop), which is what generates the help.

**Comment by rudeyak** [comment]
I'm using 0.04. I'm suggesting an edit to the help text because "Download a file off the remote host" and "Upload a file off the remote host" are so similar that I'm finding myself mixing them up when working in the server.

**Comment by iagox86** [comment]
Ahh, I understand. :)
